routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/',['as'=>'homepage', function () {
    return view('home');
}]);

Route::get('/riwayat', 'peminjamanController@index');

Route::resource('inventaris', 'inventarisController');
Route::resource('cart','cartController');
Route::resource('peminjaman','peminjamanController');
Route::get('filter/{jenis}','inventarisController@filter');
Route::get('/search/query','inventarisController@search');
Route::get('/riwayat/{id}','peminjamanController@detail');
Route::resource('detail','detailController');
Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');
Route::get('profile', 'peminjamController@index');
Route::get('/help', function () {
    return view('help');
});

Route::get('operator/peminjaman','operatorPeminjamanController@index');

resources/views/detail_p.blade.php
@extends('layouts.dashboard')

@section('title')
Detail Peminjaman
@endsection

@section('content')
<div class="container">
    <a href="{{ url('/riwayat') }}"  class="btn btn-dark" style="margin-bottom:20px">Kembali</a>
    <div class="card">
        <div class="card-body">
        
        

        
            <table class="table">
            <h2 clas="card-title">Detail peminjaman</h2>
            <tr>
                <th>Peminjam</th>
                <th>Tanggal Pinjam</th>
                <th>Tanggal Kembali</th>
                <th>Status</th>
            </tr>   

            <!-- menampilkan detail peminjaman dari controller -->
            @foreach($peminjaman as $p)
            <tr>
                <td>{{$p->peminjam}}</td>
                <td>{{$p->tanggal_pinjam}}</td>
                <td>{{$p->tanggal_kembali}}</td>
                <td>{{$p->status_peminjaman}}</td>
            </tr>
            <tr>
            <!-- Mengecek jika status peminjamannya selesai, maka tombol generate code tidak akan ditampilkan -->
                <td>@if($p->status_peminjaman == "Selesai")

                    @else
                    <a href="" class="btn btn-success" id="generateid" data-aaa="{{$p->kode}}" data-toggle="modal" data-target="#generate">Generate Kode</a>
                    @endif
                </td>
                <td colspan="3"></td>
            </tr>
            @endforeach
            </table>

    

            <table class="table table-striped">
            <hr><h2 clas="card-title">Inventaris yang dipinjam</h2>
            <tr>
                <th>Barang</th>
                <th>Kode</th>
                <th>Nama Inventaris</th>
                <th colspan="2">Keterangan</th>
            </tr>

            <!-- menampilkan data barang yang dipinjam sesuai peminjaman yang dipilih -->
            @foreach($detail as $data)
            <tr>
                <td><img src="{{asset('img/Barang/'.$data->image)}}" alt="" style="height:60px; width:60px; align:center;"></td>
                <td>{{$data->kode}}</td>
                <td>{{$data->nama}}</td>
                <td>{{$data->keterangan}}</td>

                <!-- Tombol untuk menghapus detail barang -->
                @foreach($peminjaman as $p)
                    @if($p->status_peminjaman == 'Belum Dikonfirmasi')
                        <td><form method="post" action="{{route('detail.destroy', $data->id)}}">
                        @csrf
                        <input type="hidden" name="_method" value="DELETE">
                        <input type="hidden" name="id_p" value="">
                        <input onclick="return confirm('Apakah anda yakin ingin menghapus barang?');" type="submit" class="btn btn-danger" value="Hapus">
                        </form></td>
                    @endif
                @endforeach
                
            </tr>
            @endforeach
        </table>
        </div>
    </div>
</div>

<div class="modal fade " id="generate" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered " role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h2 class="modal-title" id="kodemodal">Generate Success!</h2>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                Berikan kode ini <span id="a" class="badge badge-info">@foreach($peminjaman as $p) {{$p->kode}} @endforeach</span> kepada operator terdekat untuk memproses peminjaman / pengembalian
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/help.blade.php
@extends('layouts.dashboard')
@section('title')
Help
@endsection

@section('content')
<style>
body{
    overflow: hidden;
}
</style>
<div class="container">
    <div class="card">
        <div class="card-body">
            <strong>Cara Meminjam</strong><br><br>
            1.Pilih barang yang tersedia <br>
            2.Masukan barang ke dalam cart<br>
            3.Login dan lanjutkan request<br>
            4.Jika berhasil membuat request, anda bisa menggenerate kode untuk diberikan kepada operator<br>
            5.Tunggu hingga request anda dikonfirmasi<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
        </div>
    </div>
</div>

@endsection

resources/views/home.blade.php
@extends('layouts.dashboard')
@section('title')
ODIN
@endsection
@section('home')
<div class="banner" >
<img src="{{asset('img/9282.jpg')}}" alt="" style="width: 100%">
</div>
<div class="homepage-content-top">
    <div class="content">
        <img src="{{asset('img/content.png')}}" alt="" class="content-img">
        <span class="slogan"><b>INVENTARISIR</b> barang <br>dengan mudah dan aman<hr>
        <a href="{{route('inventaris.index')}}" class="btn btn-neutral">LIHAT INVENTARIS</a>
    </span>
    </div>
</div>
<div class="homepage-content-center">
    <img src="{{asset('img/content2.png')}}" alt="" class="content-img2">
</div>
<div class="homepage-content-bottom">
    <span class="slogan2"><b>MEMUDAHKAN</b> anda dalam <br> pencarian barang
</div>
@endsection

resources/views/inventaris.blade.php
@extends('layouts.dashboard')
@section('title')
Inventaris
@endsection
@section('content')



<div class="row">
    <div class="col-6 col-md-3" >
        <div class="card " style="margin-left: 30px; width:22rem;  border-radius:8px">

            <!-- form untuk searching data barang -->
            <span class="sidebar" style="background-color: #3d3d3d; color: white;padding: 8px; border-radius:8px"><center>SEARCH</center></span>
            <div style="padding: 20px 8px 0px 8px">
                <form method="get" action="{{url('search/query')}}">
                    @csrf
                    <div class="form-group">
                        <div class="input-group mb-4">
                            <div class="input-group-prepend">
                                <span class="input-group-text"><i class="ni ni-zoom-split-in"></i></span>
                            </div>
                            <input class="form-control" placeholder="Search" value="{{@$_GET['key']}}" name="key" type="text">
                        </div>
                        <input type="submit" style="display: none">
                    </div>
                </form>
            </div>

            <!-- div untuk memilih kategori barang -->
            <span class="sidebar" style="background-color: #3d3d3d; color: white;padding: 8px; border-radius:10px"><center>CATEGORY</center></span>
            <div style="padding: 8px; color: black">

                <!-- menampilkan data jenis barang -->
                @foreach($jenis as $j)
                <div class="category">
                    <i class="ni ni-bold-right"></i>&nbsp;<a href="{{url('filter',$j->nama_jenis)}}"  >{{$j->nama_jenis}}</a>
                </div>
                @endforeach
                <hr><a href="{{ route('cart.index') }}" style="width:100%" class="btn btn-dark"> <i class="ni ni-cart" style="font-size: 2.2em;"></i></a>
            </div>
            
            
        </div>
    </div>
    <div class="col-13 col-md-9">
        <span>
       
            <div class="card shadow" style="margin: 0 30px 20px 30px; border-radius:10px">

            <!-- alert untuk menampilkan message dari controller -->
            @if(\Session::has('success'))
                <div class="alert alert-success"><span>{{\Session::get('success')}}</span><a href="{{route('cart.index')}}" class="cek">ke dalam cart</a></div>
            @elseif(isset($_GET['key']) && $_GET['key'] !== "")
                <div class="alert alert-default"><span>Search : {{$_GET['key']}}</span></div>
            @endif

                <!-- card untuk menampilkan data inventaris -->
                <div class="card-body" >
                    <div class="row" >
                        @foreach($inv as $data)
                        <div class="col-md-4 col-md auto" style="margin-bottom:20px;">
                            <span>
                                <div class="card" style="width: 17rem; margin:40px 20px 20px; box-shadow: 0 1px 10px 0 #999; border-radius:0px;">
                                    <div class="card-img-top" alt="Card image cap">
                                    <a href="" data-ruang="{{$data->ruang}}" data-image="{{$data->image}}" data-kode="{{$data->kode}}" data-jenis="{{$data->jenis}}" data-ket="{{$data->keterangan}}" data-kondisi="{{$data->kondisi}}" data-id="{{$data->id}}" data-name="{{$data->nama}}" id="details{{$data->id}}" data-toggle="modal" data-target="#detailinv"><img src="{{asset('img/Barang/'.$data->image)}}" alt="" style="max-height: 230px; height:230px; width:100%; align:center;object-fit: cover">
                                    </div></a>
                                        
                                    <div class="card-body">
                                        <span class="card-title"><b>{{$data->nama}} </b></span> <br> <p class="badge badge-md badge-info">{{$data->kondisi}} | {{$data->kode}} | {{$data->ruang}} </p><br><br>
                                        @if($data->kondisi == "Tersedia")
                                        <form method="post" action="{{route('cart.store')}}">
                                            @csrf
                                            <input type="hidden" name="id" id="cartid" value="{{$data->id}}" required>   
                                            <input type="hidden" name="name" id="cartname" value="{{$data->nama}}" required>
                                            <input type="hidden" name="img" id="cartimg" value="{{$data->image}}" required>
                                            <input type="submit" style="width:100%" class="btn btn-dark" value="Masukan ke Keranjang">
                                        </form>
                                         @else
                                        <center><span style="padding:15px" class="badge badge-md badge-danger">Barang tidak tersedia</span></center>
                                        @endif
                                        </div>
                                </div>
                            </span>
                        </div>
                        @endforeach
                    </div>
                </div>
            </div>
        </span>
    </div>
</div>



<!-- Modal untuk menampilkan data barang  -->
<div class="modal fade" id="detailinv" tabindex="-1" role="dialog" aria-labelledby="detailinvLabel" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered" role="document">
                <div class="modal-content">
                <div class="modal-header">
                    <h2 class="modal-title" id="namabarang"> </h2>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="alert alert-neutral" role="alert">
                    <strong>DESKRIPSI PRODUK</strong>
                        <div class="alert alert-neutral" role="alert">
                            <strong>Kode</strong><p id="kode"></p>
                            <strong>Keterangan</strong><p id="keterangan"></p>
                            <strong>Kondisi</strong><p id="kondisi"></p>
                            <strong>Jenis</strong><p id="jenis"></p>
                            <strong>Ruang</strong><p id="ruang"></p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        @foreach($inv as $data)
        <script>
        //jquery untuk mengirim data barang ke dalam modal
            $(document).ready(function(){
                $("#details{{$data->id}}").click(function(){
                    var a = $("#details{{$data->id}}").data('name');
                    var b = $("#details{{$data->id}}").data('ket');
                    var c = $("#details{{$data->id}}").data('kondisi');
                    var e = $("#details{{$data->id}}").data('ruang');
                    var f = $("#details{{$data->id}}").data('jenis');
                    var g = $("#details{{$data->id}}").data('kode');
                    var g = $("#details{{$data->id}}").data('image');
                    $("#namabarang").text(a);
                    $("#keterangan").text(b);
                    $("#kondisi").text(c);
                    $("#jenis").text(f);
                    $("#ruang").text(e);
                    $("#kode").text(g);
                });
                $("#lanjutkan").click(function(){
                    $("#modaltitle").text("Login terlebih dahulu !");
                });
            });
        </script>
        @endforeach
@endsection

resources/views/profile.blade.php
@extends('layouts.dashboard')
@section('title')
Profile
@endsection

@section('content')
<style>
body{
    overflow: hidden;
}
</style>
<div class="container">
    <div class="card">
        <div class="card-body">

        <!-- menampilkan profil user -->
            @foreach($prof as $profile)
                        <strong>Nama</strong><pre>{{$profile->nama}}</pre>
                        <strong>No Induk</strong><pre>{{$profile->no_induk}}</pre>
                        <strong>Alamat</strong><pre>{{$profile->alamat}}</pre>
                        <strong>No Telepon</strong><pre>{{$profile->telepon}}</pre>
                        <strong>Jabatan</strong><pre>{{$profile->jabatan}}</pre>  
                    @endforeach <br><br><br><br><br><br><br><br><br><br><br><br><br>
        </div>
    </div>
</div>

@endsection

resources/views/riwayat.blade.php
@extends('layouts.dashboard')

@section('title')
Riwayat Peminjaman
@endsection

@section('content')

<div class="container">
    <a href="{{ url('/inventaris') }}" class="btn btn-dark" style="margin-bottom:20px">Kembali</a>
    @if(\Session::has('success'))
        <div class="alert alert-success"><span>{{\Session::get('success')}}</span></div>
    @endif
    <!-- Card untuk menampilkan peminjaman yang belum diknfirmasi -->
    <div class="card">
        <div class="card-body">
        <center>Total riwayat peminjaman <span class="badge badge-success">@foreach($total as $t) {{$t->data}}  @endforeach</span></center>    
        </div>
    </div>
    @if($dbdk->count() > 0)
    <div class="card">
        <div class="card-body">
        <h2>Peminjaman Belum Dikonfirmasi</h2><br>
            <table class="table table-striped">
                <tr>
                    <th>Kode Peminjaman</th>
                    <th>Tanggal Request</th>
                    <th colspan="2"><center>Action</center></th>
                </tr>
                @foreach($dbdk as $bdk)
                <tr>
                    <td>{{$bdk->kode}}</td>
                    <td>{{$bdk->tanggal_pinjam}}</td>
                    <td><a href="{{url('/riwayat',$bdk->id)}}" class="btn btn-success">Detail</a></td>
                    <td><form method="post" action="{{route('peminjaman.destroy', $bdk->id)}}">
                        @csrf
                        <input type="hidden" name="_method" value="DELETE">
                        <input onclick="return confirm('Apakah anda yakin ingin membatalkan request?');" type="submit" class="btn btn-danger" value="Cancel Request">
                        </form>
                    </td>
                </tr>
                @endforeach
            </table>  
        </div>
    </div>
    @else
    @endif

    @if($dsb->count() > 0)
    <hr>

    <!-- card untuk menampilkan data yang sedang berjalan -->
    <div class="card">
        <div class="card-body">
            <h2>Peminjaman Sedang Berjalan</h2><br>
            <table class="table table-striped">
                <tr>
                    <th>Kode Peminjaman</th>
                    <th>Tanggal Pinjam</th>
                    <th>Action</th>
                </tr>
                @foreach($dsb as $sb)
                <tr>
                    <td>{{$sb->kode}}</td>
                    <td>{{$sb->tanggal_pinjam}}</td>
                    <td><a href="{{url('/riwayat',$sb->id)}}" class="btn btn-success">Detail</a></td>
                </tr>
                @endforeach
            </table>    
        </div>
    </div>
    @else
    @endif

    @if($ds->count() > 0)
    <hr>

    <!-- card untuk menampilkan data peminjaman yang sudah selesai -->
    <div class="card">
        <div class="card-body">
            <h2>Peminjaman Sudah Selesai</h2><br>
            <table class="table table-striped">
                <tr>
                    <th>Kode Peminjaman</th>
                    <th>Tanggal Pinjam</th>
                    <th>Tanggal Kembali</th>
                    <th>Action</th>
                </tr>
                @foreach($ds as $s)
                <tr>
                    <td>{{$s->kode}}</td>
                    <td>{{$s->tanggal_pinjam}}</td>
                    <td>{{$s->tanggal_kembali}}</td>
                    <td><a href="{{url('/riwayat',$s->id)}}" class="btn btn-success">Detail</a></td>
                </tr>
                @endforeach
            </table>    
        </div>
    </div>
    @else
    @endif
</div><br><br><br>
@endsection