routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/',['as'=>'homepage', function () {
    return view('home');
}]);

Route::get('/riwayat', 'peminjamanController@index');

Route::resource('inventaris', 'inventarisController');
Route::resource('cart','cartController');
Route::resource('peminjaman','peminjamanController');
Route::get('filter/{jenis}','inventarisController@filter');
Route::get('/search/query','inventarisController@search');
Route::get('/riwayat/{id}','peminjamanController@detail');
Route::resource('detail','detailController');
Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');
Route::get('profile', 'peminjamController@index');
Route::get('/help', function () {
    return view('help');
});

Route::get('operator/peminjaman','operatorPeminjamanController@index');

app/Http/Controllers/cartController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Cart;
use App\peminjaman;
use App\peminjam;
use Auth;
class cartController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $cart = Cart::getContent(); //Mengambil seluruh data yang ada di session cart
        if(isset(Auth::user()->id)){
            $user = peminjam::all()->where('user_id',Auth::user()->id); //mengambil seluruh data di tabel peminjam sesuai user yang login
            foreach($user as $users){
                $pemin = peminjaman::get()->where('peminjam_id',$users['id'])->where('status_peminjaman','Belum Dikonfirmasi'); //mengambil data peminjaman sesuai user yang login dan status yang belum dikonfirmasi
                return view('cart.index', compact('cart','pemin')); //redirect ke halaman cart dengan data yang tadi di ambil
            }
        }
        else{
            return view('cart.index', compact('cart')); //redirect ke halaman cart dengan data yang tadi di ambil
        }
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //memvalidasi data yang dikirim lewat form
        $this->validate($request,[
            'id' => 'required',
            'name' => 'required',
            'img' => 'required'
        ]);

        //menambahkan data ke dalam cart session
        Cart::add(array(
            'id' => $request['id'],
            'name' => $request['name'],
            'price' => 0,
            'quantity' => 4,
            'attributes' => array('image' => $request['img'])
        ));

        //redirect ke halaman inventaris dengan pesan sukses
        return redirect('/inventaris')->with('success','1 Barang ditambahkan ');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //menghapus cart dengan id yang dikirim lewat form
        Cart::remove($id);

        //redirect ke halaman cart
        return redirect('/cart')->with('success','Berhasil menghapus barang');
    }
}

resources/views/cart/index.blade.php
@extends('layouts.dashboard')
@section('title')
Cart
@endsection

@section('content')
<div class="container">

@if(\Session::has('success'))
<div class="alert alert-info"><span>{{\Session::get('success')}}</span></div>
@endif

<a href="{{ url('/inventaris') }}" class="btn btn-dark" style="margin-bottom:20px">Kembali</a>
    <div class="card">
        <div class="card-body">
            <h1>Cart</h1>

            <!-- jika cart kosong, maka akan ditampilkan tulisan "tidak ada barang didalam cart" -->
            @if($cart->count() > 0)
            <table class="table table-striped">
                <tr>
                    <th>Barang</th>
                    <th>Kode</th>
                    <th>Nama Inventaris</th>
                    <th>Action </th>
                </tr>

                <!-- foreach untuk menampilkan data cart yang dikirim dari controller -->
               @foreach($cart as $data)
                    <tr>
                        <td><img src="{{asset('img/Barang/'.$data->attributes->image)}}" alt="" style="height:60px; width:60px; align:center;"></td>
                        <td>{{$data->id}}</td>
                        <td>{{$data->name}}</td>
                        <td><form method="post" action="{{route('cart.destroy', $data->id)}}">
                        @csrf
                        <input type="hidden" name="_method" value="DELETE">
                        <input type="submit" class="btn btn-danger"value="Hapus">
                        </form></td>
                    </tr>
               @endforeach
                <tr>
                    <td colspan="4"> 
                    @guest
                    <a href="" class="btn btn-success" id="lanjutkan" data-toggle="modal"  data-target="#login">Login untuk melanjutkan</a> 
                    @else
                    <a href="" class="btn btn-success"  data-toggle="modal" data-target="#pilihpeminjaman">Buat peminjaman baru</a>
                        <!-- jika user sudah memiliki peminjaman maka tombol tambah ke peminjaman yang yang sudah ada -->
                        @if($pemin->count() > 0)
                        <a href="" class="btn btn-info"  data-toggle="modal" data-target="#konfirmasi">Tambahkan ke peminjaman yang sudah ada</a>
                        @endif
                    @endguest
                    </td>
                </tr>
            </table>   
            @else
            <h1 style="color:lightgrey"><center>Tidak ada data di dalam cart</center></h1> 
            @endif
        </div>
    </div>
</div>
<br><br><br>
<div class="modal fade " id="konfirmasi" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered " role="document">
        <div class="modal-content">
            <div class="modal-header">
            <h2 class="modal-title">Pilih Peminjaman yang Ingin ditambahkan</h2>
            </div>
            <div class="modal-body">
            <table class="table">

            <!-- menampilkan seluruh data peminjam -->
                @if(isset($pemin))
                @foreach($pemin as $data)
                        <tr>
                            <td>{{$data->id}}</td>
                            <td>{{$data->kode}}</td>
                            <td>{{$data->tanggal_pinjam}}</td>
                            <td><form action="{{route('peminjaman.store')}}" method="POST">
                                    @csrf
                                    <input type="hidden" name="peminjaman" value="{{$data->id}}">
                                    <input type="submit" style="width:100%" value="Pilih" class="btn btn-success">
                                </form>
                            </td>
                        </tr>
                @endforeach
                @endif
                <tr>
                <td></td>
                <td colspan="3"></td>
                </tr>
            </table>
            </div>
        </div>
    </div>
</div>

<div class="modal fade " id="pilihpeminjaman" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered " role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h2 class="modal-title" id="kodemodal">
                    <form action="{{route('peminjaman.store')}}" method="POST">
                        @csrf
                        <input type="hidden" name="check" value="1">
                        <input type="submit" style="width:100%" value="Konfirmasi" class="btn btn-info">
                    </form>  </h2>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <table class="table">

                <!-- menampilkan seluruh data cart untul dikonfirmasi -->
                @foreach($cart as $data)
                        <tr>
                            <td><img src="{{asset('img/Barang/'.$data->attributes->image)}}" alt="" style="height:60px; width:60px; align:center;"></td>
                            <td>{{$data->id}}</td>
                            <td>{{$data->name}}</td>
                            <td><form method="post" action="{{route('cart.destroy', $data->id)}}">
                            @csrf
                            <input type="hidden" name="_method" value="DELETE">
                            <input type="submit" class="btn btn-danger"value="Hapus">
                            </form></td>
                        </tr>
                @endforeach
                <tr>
                <td></td>
                <td colspan="3"></td>
                </tr>
            </div>
            </table>
        </div>
    </div>
</div>
@endsection